#!/bin/bash
# ---------------------------------------------------------------------------------------
# Parameter-calibration test on the bundled Bow at Banff (CAN_05BB001) domain.
#
# Everything this needs is in the repository: the lumped SUMMA inputs and forcing, the
# mizuRoute topology and remapping, and the daily streamflow observations all live under
# utils/test/test_mizuroute/bow_real_data/. This script writes a TOML configuration
# pointing at them, runs a short DDS calibration, and checks the result.
#
# The period is deliberately tiny -- one spinup year and one calibration year, a handful
# of trials -- so the test finishes in minutes rather than hours. It exercises the
# machinery, it does not produce a calibrated parameter set.
#
# Needs an executable built with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON. Simulated streamflow for
# the objective function comes from mizuRoute, so calibration without it has nothing to
# compare against the observations.
#
# Usage:  ./test_calibration_bow.sh [n_trials] [n_ranks]
# ---------------------------------------------------------------------------------------
set -euo pipefail

TEST_DIR="$(cd "$(dirname "$0")" && pwd)"
SUMMA_ROOT="$(cd "${TEST_DIR}/../../.." && pwd)"
DATA="${SUMMA_ROOT}/utils/test/test_mizuroute/bow_real_data"
WORK="${TEST_DIR}/bow_calibration"

N_TRIALS=${1:-4}
N_RANKS=${2:-2}

SUMMA_EXE="${SUMMA_ROOT}/bin/summa_sundials_mizuroute_opt.exe"
if [ ! -x "${SUMMA_EXE}" ]; then
  SUMMA_EXE="${SUMMA_ROOT}/bin/summa_mizuroute_opt.exe"
fi
if [ ! -x "${SUMMA_EXE}" ]; then
  echo "ERROR: no calibration executable found in ${SUMMA_ROOT}/bin"
  echo "       build one with -DUSE_MPI=ON -DUSE_MIZUROUTE=ON"
  exit 1
fi

echo "======================================================================"
echo "SUMMA parameter-calibration test (Bow at Banff, bundled domain)"
echo "======================================================================"
echo "  executable:  ${SUMMA_EXE}"
echo "  domain:      ${DATA}"
echo "  work dir:    ${WORK}"
echo "  trials:      ${N_TRIALS} on ${N_RANKS} rank(s)"
echo

rm -rf "${WORK}"
mkdir -p "${WORK}/output" "${WORK}/state"

# the cold state is the starting point for every trial; keep the original pristine
cp "${DATA}/summa_inputs/coldState.nc" "${WORK}/state/"

cat > "${WORK}/config.toml" <<EOF
# generated by test_calibration_bow.sh -- a short calibration on the bundled Bow domain

[simulation]

case_name = "CAN_05BB001"

# one spinup year (1980) precedes the simulation, which the calibration then scores
start_time = "1981-01-01 00:00"
end_time   = "1981-12-31 23:00"
time_zone  = "utcTime"

# simulated streamflow for the objective comes from mizuRoute
use_mizuroute    = true
write_timeseries = false

work_path = "${WORK}/output"


[summa_files]

settings_path = "${DATA}/summa_inputs/"
forcing_path  = "${DATA}/summa_inputs/"
state_path    = "${WORK}/state/"
output_path   = "${WORK}/output/"

init_condition = "coldState.nc"
attributes     = "attributes.nc"
forcing_list   = "forcingFileList.txt"

decisions        = "modelDecisions.txt"
output_control   = "outputControl_short.txt"
trial_params     = "trialParams.nc"
local_parameters = "localParamInfo.txt"
basin_parameters = "basinParamInfo.txt"

vegetation_table = "TBL_VEGPARM.TBL"
soil_table       = "TBL_SOILPARM.TBL"
general_table    = "TBL_GENPARM.TBL"
noahmp_table     = "TBL_MPTABLE.TBL"


[mizuRoute]

namelist_path = "${DATA}/mizuroute_inputs/"
namelist_file = "mizuroute.param"

methods = "3"
dt      = 3600

write_qbasin = false
write_Qreach = false


[hydrofabric]

hfabric_path = "${DATA}/mizuroute_inputs/"
hfabric_file = "topology.nc"

dname_seg = "seg"
dname_hru = "hru"

varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"

varname_area   = "area"
varname_slope  = "slope"
varname_length = "length"

seg_outlet = 710285850


[remapping]

remap_path = "${DATA}/mizuroute_inputs/"
remap_file = "lumped_to_hru.nc"

dname_hru  = "polyid"
dname_data = "data"

vname_hruid    = "polyid"
vname_num_qhru = "nOverlaps"
vname_weight   = "weight"
vname_qhruid   = "qhru_id"


[observations]

obs_path = "${DATA}/mizuroute_inputs/"
obs_file = "CAN_05BB001_daily_flow_observations.nc"

vname_obsflow = "q_obs"


[calibration]

metric        = "kge"
obs_transform = "none"

start_date = "1981-01-01"
end_date   = "1981-12-31"

n_samples = ${N_TRIALS}

param_list = [
    "k_soil",
    "theta_sat",
    "aquiferScaleFactor",
    "routingGammaScale",
    "routingGammaShape"
]

write_aligned = false


[calibration.parameter_transformations]

k_soil = "log"
EOF

echo "Running calibration..."
set +e
mpirun -np "${N_RANKS}" "${SUMMA_EXE}" -c "${WORK}/config.toml" > "${WORK}/run.log" 2>&1
status=$?
set -e

if [ ${status} -ne 0 ]; then
  echo "FAIL: calibration exited ${status}"
  echo "--- last 25 lines of ${WORK}/run.log ---"
  tail -25 "${WORK}/run.log"
  exit 1
fi
echo "  run completed"
echo

echo "Checking calibration output..."
python3 - "${WORK}" <<'PYEOF'
import glob, os, sys
import numpy as np

work = sys.argv[1]
files = sorted(glob.glob(os.path.join(work, "output", "*.nc")))
if not files:
    print("FAIL: no output written")
    sys.exit(1)

import netCDF4 as nc

# the calibration trials file carries the objective for each trial
trial_file = None
for f in files:
    d = nc.Dataset(f)
    if any("objective" in v or "metric" in v for v in d.variables):
        trial_file = f
        break

if trial_file is None:
    print("  files written:", [os.path.basename(f) for f in files])
    print("FAIL: no objective recorded in any output file")
    sys.exit(1)

d = nc.Dataset(trial_file)
name = next(v for v in d.variables if "objective" in v or "metric" in v)
obj = np.asarray(d[name][:], dtype=float).ravel()
finite = obj[np.isfinite(obj)]

print(f"  trials file:       {os.path.basename(trial_file)}")
print(f"  objective ({name}): {finite.size} finite of {obj.size}")
if finite.size == 0:
    print("FAIL: no finite objective value")
    sys.exit(1)
print(f"  range:             {finite.min():.4f} to {finite.max():.4f}")
print(f"  best:              {finite.max():.4f}")

if not np.all(np.abs(finite) < 1e5):
    print("FAIL: objective values are not plausible")
    sys.exit(1)
print("  values:            plausible")
PYEOF

echo
echo "PASS"
